### ISSUE TITLE
4GB Error

### ISSUE THREAD

**Issue by hybridvamp** [kalanakt/All-Url-Uploader#11]
2022-07-13 05:51:56,282 - pyrogram.dispatcher - ERROR - Telegram doesn't support uploading files bigger than 2000 MiB
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/upload/upload/All-Url-Uploader/plugins/cb_buttons.py", line 17, in button
    await ddl_call_back(bot, update)
  File "/root/upload/upload/All-Url-Uploader/plugins/dl_button.py", line 147, in ddl_call_back
    await bot.send_document(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/messages/send_document.py", line 163, in send_document
    file = await self.save_file(document, progress=progress, progress_args=progress_args)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/advanced/save_file.py", line 129, in save_file
    raise ValueError("Telegram doesn't support uploading files bigger than 2000 MiB")
ValueError: Telegram doesn't support uploading files bigger than 2000 MiB

**Comment by kalanakt** [comment]
**Telegram premium benefits currently apply to users only. Premium owners' bots are still regular bots**

https://bytemeta.vip/repo/pyrogram/pyrogram/issues/1023

**Comment by vqoley** [comment]
i think it same because i am telegram premium user but got error cannot upload more than 2000mb file size.
