### ISSUE TITLE
[ bug reports ] pyrogram.dispatcher - ERROR - 'int' object is not callable

### ISSUE THREAD

**Issue by foxj0** [kalanakt/All-Url-Uploader#130]
Checklist

- [x]  I added a descriptive title
- [x] I searched for other issues and couldn't find a solution or duplication
- [x] I already searched in Google and didn't find any good information or help

**Describe the bug**
pyrogram.dispatcher - ERROR - 'int' object is not callable
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Deploy In  [e.g. locally, heroku, digital ocean]
 - Version [e.g. v.2.0.0]

**Additional context**

**Comment by foxj0** [comment]
pyrogram.dispatcher - ERROR - 'int' object is not callable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/Uploader/echo.py", line 116, in echo
    Config.PROCESS_MAX_TIMEOUT(current_time - previous_time)
TypeError: 'int' object is not callable
