### ISSUE TITLE
Total length error[ bug reports ]

### ISSUE THREAD

**Issue by Damontools32** [kalanakt/All-Url-Uploader#138]
I got this error when I want bot to download link Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/content/All-Url-Uploader/All-Url-Uploader/All-Url-Uploader/plugins/callbacks.py", line 41, in button
    await ddl_call_back(bot, update)
  File "/content/All-Url-Uploader/All-Url-Uploader/All-Url-Uploader/plugins/dl_button.py", line 85, in ddl_call_back
    await download_coroutine(
  File "/content/All-Url-Uploader/All-Url-Uploader/All-Url-Uploader/plugins/dl_button.py", line 243, in download_coroutine
    total_length = int(response.headers["Content-Length"])
KeyError: 'Content-Length

**Comment by kalanakt** [comment]
hi @Damontools32 , what kind of url you used ?
