### ISSUE TITLE
Failing Upload mp4 (No such file)

### ISSUE THREAD

**Issue by 7DSMeliodas** [kalanakt/All-Url-Uploader#74]
Checklist

- [x]  I added a descriptive title
- [x] I searched for other issues and couldn't find a solution or duplication
- [x] I already searched in Google and didn't find any good information or help

**Describe the bug**
If I send a YouTube link and try to download in mp4 I get this error:

2022-09-02 14:22:59,153 - Uploader.echo - INFO - ['yt-dlp', '--no-warnings', '--allow-dynamic-mpd', '-j', 'https://www.youtube.com/watch?v=Tb2upmuGNk8']
2022-09-02 14:23:00,992 - Uploader.echo - INFO - 
video|137|mp4|KbVte
2022-09-02 14:23:09,274 - Uploader.button - INFO - ['yt-dlp', '-c', '--max-filesize', '4194304000', '--embed-subs', '-f', '137+bestaudio', '--bidi-workaround', 'https://www.youtube.com/watch?v=Tb2upmuGNk8', '-o', './DOWNLOADS/43817863Ykgab/Frei.Wild - Feinde deiner Feinde  [Offizieller Videoclip]_137.mp4', '--no-warnings']
2022-09-02 14:23:12,938 - Uploader.button - INFO - 
2022-09-02 14:23:12,938 - Uploader.button - INFO - [youtube] Tb2upmuGNk8: Downloading webpage
[youtube] Tb2upmuGNk8: Downloading android player API JSON
[info] Tb2upmuGNk8: Downloading 1 format(s): 137+251
[download] Destination: ./DOWNLOADS/43817863Ykgab/Frei.Wild - Feinde deiner Feinde  [Offizieller Videoclip]_137.mp4.f137.mp4
[download] 100% of 62.67MiB in 00:01 at 42.96MiB/s     
[download] Destination: ./DOWNLOADS/43817863Ykgab/Frei.Wild - Feinde deiner Feinde  [Offizieller Videoclip]_137.mp4.f251.webm
[download] 100% of 2.87MiB in 00:00 at 26.74MiB/s     
[Merger] Merging formats into "./DOWNLOADS/43817863Ykgab/Frei.Wild - Feinde deiner Feinde  [Offizieller Videoclip]_137.mp4.mkv"
Deleting original file ./DOWNLOADS/43817863Ykgab/Frei.Wild - Feinde deiner Feinde  [Offizieller Videoclip]_137.mp4.f137.mp4 (pass -k to keep)
Deleting original file ./DOWNLOADS/43817863Ykgab/Frei.Wild - Feinde deiner Feinde  [Offizieller Videoclip]_137.mp4.f251.webm (pass -k to keep)
[EmbedSubtitle] There aren't any subtitles to embed
2022-09-02 14:23:12,938 - Uploader.button - INFO - [youtube] Tb2upmuGNk8: Downloading webpage
[youtube] Tb2upmuGNk8: Downloading android player API JSON
[info] Tb2upmuGNk8: Downloading 1 format(s): 137+251
[download] Destination: ./DOWNLOADS/43817863Ykgab/Frei.Wild - Feinde deiner Feinde  [Offizieller Videoclip]_137.mp4.f137.mp4
[download] 100% of 62.67MiB in 00:01 at 42.96MiB/s     
[download] Destination: ./DOWNLOADS/43817863Ykgab/Frei.Wild - Feinde deiner Feinde  [Offizieller Videoclip]_137.mp4.f251.webm
[download] 100% of 2.87MiB in 00:00 at 26.74MiB/s     
[Merger] Merging formats into "./DOWNLOADS/43817863Ykgab/Frei.Wild - Feinde deiner Feinde  [Offizieller Videoclip]_137.mp4.mkv"
Deleting original file ./DOWNLOADS/43817863Ykgab/Frei.Wild - Feinde deiner Feinde  [Offizieller Videoclip]_137.mp4.f137.mp4 (pass -k to keep)
Deleting original file ./DOWNLOADS/43817863Ykgab/Frei.Wild - Feinde deiner Feinde  [Offizieller Videoclip]_137.mp4.f251.webm (pass -k to keep)
[EmbedSubtitle] There aren't any subtitles to embed
2022-09-02 14:23:12,939 - pyrogram.dispatcher - ERROR - [Errno 2] No such file or directory: './DOWNLOADS/43817863Ykgab/Frei.Wild - Feinde deiner Feinde  [Offizieller Videoclip]_137.mkv'
Traceback (most recent call last):
  File "/home/Bots/YTBot/All-Url-Uploader/Uploader/button.py", line 198, in youtube_dl_call_back
    file_size = os.stat(download_directory).st_size
FileNotFoundError: [Errno 2] No such file or directory: './DOWNLOADS/43817863Ykgab/Frei.Wild - Feinde deiner Feinde  [Offizieller Videoclip]_137.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Bots/.local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/Bots/YTBot/All-Url-Uploader/Uploader/callbacks.py", line 63, in button
    await youtube_dl_call_back(bot, update)
  File "/home/Bots/YTBot/All-Url-Uploader/Uploader/button.py", line 203, in youtube_dl_call_back
    file_size = os.stat(download_directory).st_size
FileNotFoundError: [Errno 2] No such file or directory: './DOWNLOADS/43817863Ykgab/Frei.Wild - Feinde deiner Feinde  [Offizieller Videoclip]_137.mkv'

**Expected behavior**
Upload the video in mp4

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Deploy In  VPS
 - Version 2.0.2

**Comment by 7DSMeliodas** [comment]
webm seems to work
