### ISSUE TITLE
VPS Running error issue

### ISSUE THREAD

**Issue by devilevil1** [kalanakt/All-Url-Uploader#81]
Checklist

**Screenshots**
Traceback (most recent call last):
  File "/home/ubuntu/All-Url-Uploader/bot.py", line 52, in <module>
    Uploadbot.run()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyrogram/methods/utilities/run.py", line 84, in run
    self.start()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyrogram/client.py", line 574, in load_session
    raise AttributeError("The API key is required for new authorizations. "

**Comment by kalanakt** [comment]
working on it

**Comment by niranjantechofficial** [comment]
Now its working ??

**Comment by devilevil1** [comment]
No now it's showing something api authentication issue

**Comment by pr13260** [comment]
Either your api id and hash combination is incorrect or you have left it empty

**Comment by MohamadBayz** [comment]
Don't change `Uploader/config.py` left it untouched, instead change `sample_config.py` in the main folder
As it states in readme doc
https://github.com/kalanakt/All-Url-Uploader/blob/main/Uploader/README.md

**Comment by lahirubandara123** [comment]
> Don't change `Uploader/config.py` left it untouched, instead change `sample_config.py` in the main folder As it states in readme doc https://github.com/kalanakt/All-Url-Uploader/blob/main/Uploader/README.md

It worked. Thank you very much sir. 😍😍😍There was no way to save videos in my class. At first I used Heroku and then tried Railway and Render when it stopped. But did not succeed. After that I always downloaded the video to my computer and uploaded it again. It's a big headache. After that I bought a VPS. But that didn't work either. I edited the Config.py file. That is the error. Thank you very much sir. There was a small mistake. I spent money for the VPS for nothing. Thank you very much sir you are a life saver. :) 😍😍😍😍😍😍😍🥰🥰🥰🥰🥰😎😎
